[build]
  publish = "."
  functions = "netlify/functions" # This line is crucial for Netlify to find your functions

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
